### ISSUE TITLE
GET /sites

### ISSUE THREAD

**Issue by Lyokolux** [compostage-dans-ma-ville/backend#11]
## Description

A list of sites can be retrieved.

## DoD
- [x] the endpoint matches `GET /sites`
- [x] a test checks that the endpoint return some site
- [x] a pagination is set up
  - [x] a defined amount of sites can be retrieved
  - [x] the total amount of pages is provided
  - [x] a specific page can be fetched
  - [x] next and previous page link are provided, if possible
  - [x] first and last page are provided
- [ ]  A site can be queried based on a localisation and a range of kms (→ move to another ticket)

**Comment by Lyokolux** [comment]
Il semble préférable de séparer la pagination des liens en deux classes.

Pagination:
```ts
class Pagination {
  pageNumber: number
  pageSize: number
  totalCount: number
}
```

Links:
```ts
class Links {
  prev?: string
  next?: string
  last: string
  first: string
}
```

TODO: how to document this?

**Comment by johannchopin** [comment]
Ça me semble pas mal 👍 A voir comment sa s'intégre avec nest et prisma 🤔

**Comment by Lyokolux** [comment]
> Ça me semble pas mal 👍 A voir comment sa s'intégre avec nest et prisma 🤔

Tkt
