### ISSUE TITLE
Rendre DailySchedules optionnel dans un Site

### ISSUE THREAD

**Issue by johannchopin** [compostage-dans-ma-ville/backend#39]
Un site n'a pas forcément de DailySchedules (ex: les sites privés à cadenas).

**Comment by Lyokolux** [comment]
@johannchopin quels sont les critères pour que tu juges ce ticket comme résolu?

**Comment by johannchopin** [comment]
Juste modifier le schéma prisma et dto j'aurais dit 🤔

**Comment by Lyokolux** [comment]
L'API retourne alors `schedule: null`, `schedule: undefined` ou simplement l'objet sans la propriété `schedule` ?

**Comment by Lyokolux** [comment]
> Juste modifier le schéma prisma et dto j'aurais dit thinking

Le schéma possède une relation multiple, donc par défaut, un tableau vide est retourné. Cela peut cependant prêter à confusion. `null` ou `undefined` serait plus adapté.

En revanche, de quoi as-tu besoin pour l'UI?
