### ISSUE TITLE
GET /users

### ISSUE THREAD

**Issue by johannchopin** [compostage-dans-ma-ville/backend#63]
Permet d'avoir tous les utilisateurs avec pagination. Je ne suis pas sûre du use case de cet endpoint si ce n'est REST donc je set la prio à **low**.

**Comment by johannchopin** [comment]
@Lyokolux ce ticket est en low est-ce une erreur qu'il soit in progress? 🤔

**Comment by Lyokolux** [comment]
Nope, c'est un facile, donc autant l'implémenter
