### ISSUE TITLE
Gérer le type des sites

### ISSUE THREAD

**Issue by johannchopin** [compostage-dans-ma-ville/backend#68]
Un site peut avoir un des types suivant:

- compostage partagée -> pied d'immeuble
- établissement scolaire
- établissement administratif
- entreprise

Implémenter l'enum dans prisma

**Comment by Lyokolux** [comment]
Est-ce que le type peut être indéfini?

**Comment by Lyokolux** [comment]
@johannchopin depuis les données j'ai les types suivants:
* "autre_dechets_verts"
* "autre_etablissement"
* "autre_partage"
* "EHPAD"
* "etab_touristique"
* "ferme"
* "milieu_hospitalier"
* "ne sait pas"
* null
* "pied_immeuble"
* "plateforme_communale"
* "quartier"
* "resto_administratif"
* "resto_entreprise"
* "scolaire"
"vermicompostage"

---

Je constates 2 types de site:
* selon la nature du site
  * quartier
  * pied_immeuble
  * autre_partage
  * autre_dechets_verts
* selon le "fournisseur" du site
  * scolaire
  * resto_entreprise
  * resto_administratif 
  * plateforme_communale
  * autre_etablissement
  * EHPAD
  * etab_touristique
  * ferme
  * milieu_hospitalier
